name: Deploy to Cloud Run

on:
  workflow_dispatch:  # ✅ Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      REGION: us-central1
      SERVICE_NAME: spotify-playback-tracker

    defaults:
      run:
        working-directory: cloud/playback

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_KEY_JSON }}

      - name: Authenticate Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars "SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }},SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }},SPOTIPY_REDIRECT_URI=${{ secrets.SPOTIPY_REDIRECT_URI }},SPOTIPY_REFRESH_TOKEN=${{ secrets.SPOTIPY_REFRESH_TOKEN }},GCP_PROJECT=${{ secrets.GCP_PROJECT }},BQ_DATASET=${{ secrets.BQ_DATASET }},BQ_TABLE=${{ secrets.BQ_TABLE }}"