name: Spotify Data Pipeline

on:
  workflow_dispatch:        # Manual trigger via GitHub UI
  schedule:
    - cron: '0 16 * * *'     # Run every day at 4PM UTC
  push:
    branches:
      - ci-github-secrets    # Trigger on pushes to your dev branch
  pull_request:
    branches:
      - main                 # Trigger when PR targets main

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      BQ_DATASET: ${{ secrets.BQ_DATASET }}
      BQ_TABLE: ${{ secrets.BQ_TABLE }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install spotipy google-cloud-bigquery

      - name: Decode GCP key
        run: |
          echo "${{ secrets.GCP_KEY_B64 }}" | base64 -d > gcp_key.json

      - name: Run Spotify Script
        run: |
          GOOGLE_APPLICATION_CREDENTIALS="gcp_key.json" python spotify_to_bigquery.py
        